from .detect_language_schema import DetectLanguage
from .detected_language_schema import DetectedLanguage
from .text_to_translate_schema import TextToTranslate
from .translated_text_schema import TranslatedText
